import { useTheme } from '@mui/material';

const NavDefaultStylesConfig = (): any => {
  const theme = useTheme();

  return {
    ROOT_ITEM_BUTTON_BORDER_RADIUS: '6px',
    ROOT_ITEM_BUTTON_HEIGHT: 46,
    ROOT_ITEM_BUTTON_PADDING_X: 12,
    ROOT_ITEM_BUTTON_PADDING_Y: 5,
    ROOT_ITEM_BUTTON_MARGIN_X: 5,
    ROOT_ITEM_BUTTON_MARGIN_Y: 2,
    ROOT_ITEM_BUTTON_BACKGROUND_COLOR_HOVER: theme.palette.grey['100'],
    ROOT_ITEM_BUTTON_BACKGROUND_COLOR_OPEN: 'transparent',
    ROOT_ITEM_BUTTON_BACKGROUND_COLOR_HERE: 'transparent',
    ROOT_ITEM_BUTTON_BACKGROUND_COLOR_ACTIVE: theme.palette.primary.light,
    ROOT_ITEM_TITLE_FONT_SIZE: 15,
    ROOT_ITEM_TITLE_FONT_WEIGHT: theme.typography.fontWeightBold,
    ROOT_ITEM_TITLE_COLOR: theme.palette.grey['700'],
    ROOT_ITEM_TITLE_COLOR_HOVER: theme.palette.grey['900'],
    ROOT_ITEM_TITLE_COLOR_OPEN: theme.palette.grey['900'],
    ROOT_ITEM_TITLE_COLOR_HERE: theme.palette.grey['900'],
    ROOT_ITEM_TITLE_COLOR_ACTIVE: theme.palette.primary.main,
    ROOT_ITEM_ICON_SIZE: 18,
    ROOT_ITEM_ICON_FONT_SIZE: 16,
    ROOT_ITEM_ICON_GAP: theme.spacing(1),
    ROOT_ITEM_ICON_COLOR: theme.palette.grey['500'],
    ROOT_ITEM_ICON_COLOR_HOVER: theme.palette.grey['700'],
    ROOT_ITEM_ICON_COLOR_OPEN: theme.palette.grey['700'],
    ROOT_ITEM_ICON_COLOR_HERE: theme.palette.grey['700'],
    ROOT_ITEM_ICON_COLOR_ACTIVE: theme.palette.primary.main,
    ROOT_ITEM_BULLET_GAP: 4,
    ROOT_ITEM_BULLET_HEIGHT: 4,
    ROOT_ITEM_BULLET_WIDTH: 4,
    ROOT_ITEM_BULLET_BORDER_RADIUS: '50%',
    ROOT_ITEM_BULLET_COLOR: theme.palette.grey['500'],
    ROOT_ITEM_BULLET_COLOR_HOVER: theme.palette.grey['700'],
    ROOT_ITEM_BULLET_COLOR_OPEN: theme.palette.grey['700'],
    ROOT_ITEM_BULLET_COLOR_HERE: theme.palette.grey['700'],
    ROOT_ITEM_BULLET_COLOR_ACTIVE: theme.palette.primary.main,
    ROOT_ITEM_ARROW_SIZE: 16,
    ROOT_ITEM_ARROW_FONT_SIZE: 15,
    ROOT_ITEM_ARROW_COLOR: theme.palette.grey['500'],
    ROOT_ITEM_ARROW_COLOR_HOVER: theme.palette.grey['700'],
    ROOT_ITEM_ARROW_COLOR_OPEN: theme.palette.grey['700'],
    ROOT_ITEM_ARROW_COLOR_HERE: theme.palette.grey['700'],
    ROOT_ITEM_ARROW_COLOR_ACTIVE: theme.palette.primary.main,

    SUB_INDENTION: 1.15,
    SUB_ITEM_BUTTON_BORDER_RADIUS: '6px',
    SUB_ITEM_BUTTON_HEIGHT: 46,
    SUB_ITEM_BUTTON_PADDING_X: 12,
    SUB_ITEM_BUTTON_PADDING_Y: 5,
    SUB_ITEM_BUTTON_GAP: '2px',
    SUB_ITEM_BUTTON_MARGIN_X: 5,
    SUB_ITEM_BUTTON_MARGIN_Y: 2,
    SUB_ITEM_BUTTON_BACKGROUND_COLOR_HOVER: theme.palette.grey['100'],
    SUB_ITEM_BUTTON_BACKGROUND_COLOR_OPEN: 'transparent',
    SUB_ITEM_BUTTON_BACKGROUND_COLOR_HERE: 'transparent',
    SUB_ITEM_BUTTON_BACKGROUND_COLOR_ACTIVE: theme.palette.primary.light,
    SUB_ITEM_TITLE_FONT_SIZE: 15,
    SUB_ITEM_TITLE_FONT_WEIGHT: theme.typography.fontWeightBold,
    SUB_ITEM_TITLE_COLOR: theme.palette.grey['600'],
    SUB_ITEM_TITLE_COLOR_HOVER: theme.palette.grey['700'],
    SUB_ITEM_TITLE_COLOR_OPEN: theme.palette.grey['700'],
    SUB_ITEM_TITLE_COLOR_HERE: theme.palette.grey['700'],
    SUB_ITEM_TITLE_COLOR_ACTIVE: theme.palette.primary.main,
    SUB_ITEM_ICON_SIZE: 18,
    SUB_ITEM_ICON_FONT_SIZE: 15,
    SUB_ITEM_ICON_GAP: theme.spacing(1),
    SUB_ITEM_ICON_COLOR: theme.palette.grey['400'],
    SUB_ITEM_ICON_COLOR_HOVER: theme.palette.grey['500'],
    SUB_ITEM_ICON_COLOR_OPEN: theme.palette.grey['500'],
    SUB_ITEM_ICON_COLOR_HERE: theme.palette.grey['500'],
    SUB_ITEM_ICON_COLOR_ACTIVE: theme.palette.primary.main,
    SUB_ITEM_BULLET_GAP: 1.5,
    SUB_ITEM_BULLET_HEIGHT: 4,
    SUB_ITEM_BULLET_WIDTH: 4,
    SUB_ITEM_BULLET_BORDER_RADIUS: '50%',
    SUB_ITEM_BULLET_COLOR: theme.palette.grey['400'],
    SUB_ITEM_BULLET_COLOR_HOVER: theme.palette.grey['500'],
    SUB_ITEM_BULLET_COLOR_OPEN: theme.palette.grey['500'],
    SUB_ITEM_BULLET_COLOR_HERE: theme.palette.grey['500'],
    SUB_ITEM_BULLET_COLOR_ACTIVE: theme.palette.primary.main,
    SUB_ITEM_ARROW_SIZE: 16,
    SUB_ITEM_ARROW_FONT_SIZE: 15,
    SUB_ITEM_ARROW_COLOR: theme.palette.grey['400'],
    SUB_ITEM_ARROW_COLOR_HOVER: theme.palette.grey['500'],
    SUB_ITEM_ARROW_COLOR_OPEN: theme.palette.grey['500'],
    SUB_ITEM_ARROW_COLOR_HERE: theme.palette.grey['500'],
    SUB_ITEM_ARROW_COLOR_ACTIVE: theme.palette.primary.main,

    MENU_WIDTH: '200px',
    MENU_PADDING_X: 0,
    MENU_PADDING_Y: 8,
    MENU_BOX_SHADOW: theme.customShadows.menu,
    MENU_BORDER_RADIUS: '6px',
    MENU_BACKGROUND_COLOR: theme.palette.background.paper,
    MENU_ITEM_BUTTON_BORDER_RADIUS: '6px',
    MENU_ITEM_BUTTON_HEIGHT: 38,
    MENU_ITEM_BUTTON_PADDING_X: 12,
    MENU_ITEM_BUTTON_PADDING_Y: 5,
    MENU_ITEM_BUTTON_MARGIN_X: 8,
    MENU_ITEM_BUTTON_MARGIN_Y: 2,
    MENU_ITEM_BUTTON_BACKGROUND_COLOR_HOVER: theme.palette.grey['100'],
    MENU_ITEM_BUTTON_BACKGROUND_COLOR_OPEN: 'transparent',
    MENU_ITEM_BUTTON_BACKGROUND_COLOR_HERE: 'transparent',
    MENU_ITEM_BUTTON_BACKGROUND_COLOR_ACTIVE: theme.palette.primary.light,
    MENU_ITEM_TITLE_FONT_SIZE: 14,
    MENU_ITEM_TITLE_FONT_WEIGHT: theme.typography.fontWeightMedium,
    MENU_ITEM_TITLE_COLOR: theme.palette.grey['600'],
    MENU_ITEM_TITLE_COLOR_HOVER: theme.palette.grey['800'],
    MENU_ITEM_TITLE_COLOR_OPEN: theme.palette.grey['800'],
    MENU_ITEM_TITLE_COLOR_HERE: theme.palette.grey['800'],
    MENU_ITEM_TITLE_COLOR_ACTIVE: theme.palette.primary.main,
    MENU_ITEM_ICON_SIZE: 18,
    MENU_ITEM_ICON_FONT_SIZE: 15,
    MENU_ITEM_ICON_GAP: 5,
    MENU_ITEM_ICON_COLOR: theme.palette.grey['400'],
    MENU_ITEM_ICON_COLOR_HOVER: theme.palette.grey['500'],
    MENU_ITEM_ICON_COLOR_OPEN: theme.palette.grey['500'],
    MENU_ITEM_ICON_COLOR_HERE: theme.palette.grey['500'],
    MENU_ITEM_ICON_COLOR_ACTIVE: theme.palette.primary.main,
    MENU_ITEM_BULLET_GAP: 1.5,
    MENU_ITEM_BULLET_HEIGHT: 4,
    MENU_ITEM_BULLET_WIDTH: 4,
    MENU_ITEM_BULLET_BORDER_RADIUS: '50%',
    MENU_ITEM_BULLET_COLOR: theme.palette.grey['400'],
    MENU_ITEM_BULLET_COLOR_HOVER: theme.palette.grey['500'],
    MENU_ITEM_BULLET_COLOR_OPEN: theme.palette.grey['500'],
    MENU_ITEM_BULLET_COLOR_HERE: theme.palette.grey['500'],
    MENU_ITEM_BULLET_COLOR_ACTIVE: theme.palette.primary.main,
    MENU_ITEM_ARROW_SIZE: 16,
    MENU_ITEM_ARROW_FONT_SIZE: 15,
    MENU_ITEM_ARROW_COLOR: theme.palette.grey['400'],
    MENU_ITEM_ARROW_COLOR_HOVER: theme.palette.grey['500'],
    MENU_ITEM_ARROW_COLOR_OPEN: theme.palette.grey['500'],
    MENU_ITEM_ARROW_COLOR_HERE: theme.palette.grey['500'],
    MENU_ITEM_ARROW_COLOR_ACTIVE: theme.palette.primary.main,

    SUBHEADER_FONT_SIZE: 11,
    SUBHEADER_PADDING_TOP: theme.spacing(3),
    SUBHEADER_PADDING_BOTTOM: theme.spacing(1),
    SUBHEADER_COLOR: theme.palette.text.secondary,

    BADGE_FONT_SIZE: 11,
    BADGE_FONT_WEIGHT: theme.typography.fontWeightMedium,
    BADGE_GAP: 2,

    DIVIDER_MARGIN_Y: 5,
    DIVIDER_BORDER: '1px dashed ' + theme.palette.grey['300']
  };
};

export { NavDefaultStylesConfig };
