const LAYOUT_AUTH = {};

const LAYOUT_DEFAULT = {
  SIDEBAR_WIDTH: 300,
  SIDEBAR_COLLAPSE_WIDTH: 80,
  SIDEBAR_WIDTH_MOBILE: 250,
  SIDEBAR_TRANSITION_DURATION: "0.3s",
  SIDEBAR_TRANSITION_TIMING_FUNCTION: "ease",
};

export { LAYOUT_AUTH, LAYOUT_DEFAULT };
