import type { Metadata, NextPage } from 'next'
import type { AppProps } from 'next/app'
import {ReactElement, ReactNode, useEffect} from 'react'
import {ProvidersWrapper} from "@/providers"
import '@/components/keenicons/assets/duotone/style.css';
import '@/components/keenicons/assets/outline/style.css';
import '@/components/keenicons/assets/solid/style.css';
import "@/css/styles.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}

export default function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  useEffect(() => {
    document.children[0].classList.add("h-full");
    document.body.classList.add("flex");
    document.body.classList.add("flex-col");
    document.body.classList.add("h-full");
    document.body.classList.add("light");
    document.getElementById("__next")?.classList.add("flex");
    document.getElementById("__next")?.classList.add("grow");
  }, []);

  // Use the layout defined at the page level, if available
  const getLayout = Component.getLayout || ((page) => page)
 
  return <ProvidersWrapper>
    {getLayout(<Component {...pageProps} />)}
  </ProvidersWrapper>
}