import type { Metadata, NextPage } from 'next'
import type { AppProps } from 'next/app'
import {ReactElement, ReactNode, useEffect} from 'react'
import '@/components/keenicons/assets/duotone/style.css';
import '@/components/keenicons/assets/outline/style.css';
import '@/components/keenicons/assets/solid/style.css';
import "@/css/styles.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}

export default function MyApp({ Component, pageProps }: AppPropsWithLayout) {

  // Use the layout defined at the page level, if available
  const getLayout = Component.getLayout || ((page) => page)
 
  return getLayout(<Component {...pageProps} />)
}