name: RELEASE DEPLOY

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: 1. Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 2. Build Metronic Tailwind React
        run: |
          yarn install
          CI=false yarn build
          ls
        working-directory: typescript/vite

      - name: 3. Publish Metronic Tailwind React
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          password: ${{ secrets.SSH_PROD_PSW }}
          port: 22
          source: './typescript/vite/dist/*'
          target: '~/var/www/keenthemes.com/current/public/metronic/tailwind/react'
          rm: true

      - name: 19. Results
        run: |
          echo "https://keenthemes.com/metronic/tailwind/react/"